name: Lumina Gate

on:
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  gate:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Dotnet info
        run: dotnet --info

      - name: Ensure EF tools
        run: dotnet tool install --global dotnet-ef || dotnet tool update --global dotnet-ef

      - name: Add tools to PATH
        shell: pwsh
        run: |
          $toolPath = "$env:USERPROFILE\.dotnet\tools"
          echo "$toolPath" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Run Lumina Gate (non-fatal)
        shell: pwsh
        continue-on-error: true
        run: |
          .\tools\gates\lumina-gate.ps1 `
            -SolutionPath ".\InCareSys.SelfHealth\InCareSys.SelfHealth.sln" `
            -SharedProject ".\InCareSys.SelfHealth\InCareSys.SelfHealth.Shared\InCareSys.SelfHealth.Shared.csproj" `
            -StartupProject ".\InCareSys.SelfHealth\InCareSys.SelfHealth.Web\InCareSys.SelfHealth.Web.csproj" `
            -AppSettingsPath ".\InCareSys.SelfHealth\InCareSys.SelfHealth.Web\appsettings.Development.json" `
            -Environment "CI"

      - name: Upload Lumina results
        uses: actions/upload-artifact@v4
        with:
          name: lumina-gate-results
          path: InCareSys.SelfHealth/InCareSys.SelfHealth.Shared/wwwroot/docs/Architecture/Gates/results/*.json
          if-no-files-found: warn
